"""
print("hello World")
print("heyy")
print(1+2*2)

#Data type/ exe 4.1 /pg. 13

print("Flynn")
print("Mrs White")
print("King's High")
print("15")
print("2047")
print("115")
print(658/7)
print("A long time ago")
print("candy crush")
print("Digi Tec")


#Data type/ exe 4.4 /pg. 17 
print("")
print("Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you")
print("Starwars ep.1 the phantom menace \n ex squeeze me ")
print("\n")
print("a string is a line of characters incased in quotation marks")
print("\n")
print("an interger is a whole number")
print("\n")
print("a float is the opisite of a number because it includes fractions of numbers")
print("\n")
print(543/3)
print("\n")
print(543%3)
print("\n")
print(1000%9)
print("\n")
print(434/10)
print("\n")
print(3%2)
print("\n")
print(5%5)
print("\n")
print(555/2)
print("\n")
print(123/2)
print("\n")
print(123//2)
print("\n")
print(123%2)
print("\n")
print(764%2)
print("\n")
print(165//2)
print("\n")
print(float(44+10))
print("\n")
print(int(1+15))
print("\n")
print(float(10-1.1))
print("\n")
print(float(12.3-2))
print("\n")
print(6/5)
print("\n")
print(6.1-5)
print("\n")
print(6*5.5)
print("\n")
print(5*5)
print("\n")
print('Flynn'*10)
print("\n")
print('Flynn \n'*10)
print("\n")
print("5+10=" + str(5+10))
print("\n")
print("15/2=" + str(15/2))
print("\n")
print("30/2*5=" + str(30/2*5))
print("\n")
print("30/2*5=" + str(30/2*5))

#Data type/ exe 5.4 /pg. 19 
                                                                                                       
player_lives = 3 
print("\n")
user_username = 'flymc24'
print("\n")
user_money = 5
print("\n")
user_num =str('0220264585')
print("\n")
user_name = 'Flynn'
print("\n")
user_age = 14
print('\n')
var_name = input(print('what is your name?'))
print(f'your name is {var_name}')
print('\n')
var_age = input(print('what is your age?'))
print(f'your age is {var_age}')
print('\n')
var_year = input(print('what is the year?'))
print(f'the year is {var_year}')
print('\n')
var_age = input(print('what is your age?'))
print(f'your age is {var_age}')
print('\n')
var_surname = input(print('what is your surname?'))
print(f'your surname is {var_surname}')
print('\n')
var_school = input(print('what school do you go to?'))
print(f'your school is {var_school}')
print('\n')
var_favfood = input(print('what is your favourite food?'))
print(f'your favourite food is {var_favfood}')
print('\n')
var_petname = input(print('what is your pets name?'))
print(f'your pets name is {var_petname}')
print('\n')
var_num_blockchocolate = input(print('how many blocks of chocolate to you have?'))
print(f'you have {var_var_num_blockchocolate} blocks of chocolate')
print('\n')
var_player_score = input(print('how many scores have you made?'))
print(f'you made {var_player_score} scores')
print('\n')
var_highscore = input(print('what is your high score?'))
print(f'your high score is {var_highscore}')
print('\n')
var_laps = input(print('how many laps have you done?'))
print(f'you have done {var_laps} laps')
print('\n')
ammo = 5
print('\n')
gear = 5
print('\n')
player_speed = 250
print('\n')
"""   
#Data type/ exe 6.3 /pg. 23 

input('press any key')
print('\n')
input('whats your name?')
print('\n')
input('how old are you?')
print('\n')
user_name=input('whats your name?')
print('\n')
user_age=input('whats your age?')
print('\n')
user_favmovie=input('whats your favourite movie?')
print('\n')
user_book=input('whats your book called?')
print('\n')
user_adjective=input('whats an adjective?')
print('\n')
user_noun=input('whats your pronouns?')
print('\n')
user_verb=input('whats a verb?')
print('\n')
print('your name is {user_name}')
print('\n')
print('your age is {user_age}')
print('\n')
print('your favourite movie is {user_favmovie}')
print('\n')
print('your favourite book is {user_book}')
print('\n')
print('your adjectives are  is {user_adjective}')
print('\n')
print('your noun is {user_noun}')
print('\n')
print('your verbs are {user_verb}')
print('\n')
user_age=input('whats your age?')
print(int({user_age} + 10))
print('\n')
print(2022 - {user_age})


