"""
print("hello World")
print("heyy")
print(1+2*2)

#Data type/ exe 4.1 /pg. 13

print("Flynn")
print("Mrs White")
print("King's High")
print("15")
print("2047")
print("115")
print(658/7)
print("A long time ago")
print("candy crush")
print("Digi Tec")

"""

#Data type/ exe 4.4 /pg. 17 
print("")
print("Never gonna give you up Never gonna let you down Never gonna run around and desert you Never gonna make you cry Never gonna say goodbye Never gonna tell a lie and hurt you")
print("Starwars ep.1 the phantom menace \n ex squeeze me ")
print("\n")
print("a string is a line of characters incased in quotation marks")
print("\n")
print("an interger is a whole number")
print("\n")
print("a float is the opisite of a number because it includes fractions of numbers")
print("\n")
print(543/3)
print("\n")
print(543%3)
print("\n")
print(1000%9)
print("\n")
print(434/10)
print("\n")
print(3%2)
print("\n")
print(5%5)
print("\n")
print(555/2)
print("\n")
print(123/2)
print("\n")
print(123//2)
print("\n")
print(123%2)
print("\n")
print(764%2)
print("\n")
print(165//2)
print("\n")
print()
